ci: Add GitHub Actions to build OpenXR-CTS for Android
KhronosGroup/OpenXR-CTS pull request #34
Opened 2022-01-29 04:28 UTC by utzcoz

2022-01-29 04:49 UTC, utzcoz commented
Looks like the PR that adds GitHub Workflow firstly will not run.

2022-02-16 16:41 UTC, rpavlik requested changes
Looks good, I presume it's based on my workflow for hello_xr. Just one little tweak and we can get this merged. Thanks so much!

2022-02-16 16:41 UTC, rpavlik commented on .github/workflows/android-OpenXR-CTS-ci.yml
> +  build-helloxr:
Probably change the job name :grin:

2022-02-17 04:06 UTC, utzcoz commented on .github/workflows/android-OpenXR-CTS-ci.yml
> +  build-helloxr:
Done. Thanks.

2022-02-17 04:15 UTC, utzcoz commented
> Looks good, I presume it's based on my workflow for hello_xr. Just one little tweak and we can get this merged. Thanks so much!

Yep :). I copied from OpenXR-SDK-Source, and changed something for OpenXR-CTS.

2022-02-18 03:57 UTC, rpavlik approved these changes
Looks good! I'll merge it after I tag the release I'm finishing up right now

2022-02-24 17:34 UTC, rpavlik approved these changes

2022-02-24 17:34 UTC, merged

2022-02-25 00:33 UTC, utzcoz commented
Thanks.

2022-02-25 03:18 UTC, rpavlik commented
Thank you!