Load and run XR_APILAYER_KHRONOS_runtime_conformance layer for android
KhronosGroup/OpenXR-CTS pull request #38
Opened 2022-05-29 15:47 UTC by idrisshah

2022-05-29 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/OpenXR-CTS?pullRequest=38) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/OpenXR-CTS?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/OpenXR-CTS?pullRequest=38) it.</sub>

2022-06-13 19:56 UTC, rpavlik requested changes

2022-06-13 19:56 UTC, rpavlik commented on src/conformance/build.gradle
> +    from('.cxx/cmake/debug/x86_64/src/conformance/conformance_layer/') {
This is specific to one architecture and build config, need something more generic (if we still use manifests - Vulkan loader on Android doesn't use manifests at all)

2022-06-13 19:56 UTC, rpavlik commented on src/loader/manifest_file.cpp
> +    api_version.patch = 0;
Much of this function looks copy and pasted from other code: prefer factoring the other code so that it can be re-used instead of being duplicated.

2022-06-13 23:59 UTC, idrisshah commented on src/conformance/build.gradle
> +    from('.cxx/cmake/debug/x86_64/src/conformance/conformance_layer/') {
For the [specs](https://www.khronos.org/registry/OpenXR/specs/1.0/loader.html#android-runtime-negotiation), it is clear that Android loader does not use manifest file. So in that case, this whole patch is wrong and needs to be re-written. right?

2022-06-14 18:18 UTC, rpavlik commented on src/conformance/build.gradle
> +    from('.cxx/cmake/debug/x86_64/src/conformance/conformance_layer/') {
I mean, that loader spec is somewhat of a living document, and nobody is loading layers (except maybe oculus?) so there's room to adjust it to match reality, but yeah, I'd agree that it is probable that we don't need that manifest-parsing code anymore. At least, I think that's what the understanding was with other WG members (that we'd just look right for libraries with the right filename as vulkan does).

What I did with the runtime detection part on Android, is create (in-memory) the json objects corresponding to "what would have been" the manifest, so we can share code paths. You may wish to do the same here.

2022-06-14 19:31 UTC, idrisshah commented on src/conformance/build.gradle
> +    from('.cxx/cmake/debug/x86_64/src/conformance/conformance_layer/') {
Ok. That seems like a doable task. I will work on it.

2022-06-27 10:03 UTC, chenxuanyu reviewed
Will this change be synchronized to the monado code base ？

2022-06-27 14:28 UTC, rpavlik commented
There shouldn't need to be any changes for Monado to use the results of this when it's done. I haven't tested Monado with the layer on Android but we've tested it on desktop, and others have tested Monado-based runtimes with the layer on Android.

2022-06-28 06:24 UTC, chenxuanyu commented
Thank you for your reply.   you mean You'll update the CTS code ,How soon can I update it

2022-07-20 07:51 UTC, chenxuanyu commented
Merging is blocked ,please Handle as soon as possible，we are waiting now

2022-07-20 14:14 UTC, rpavlik commented
@chenxuanyu Until this is ready, you'll need to either modify it yourself and merge it locally, or install the conformance layer system-wide. If your company is a Khronos member, you can reach out on the Khronos OpenXR chat, in the Conformance room, for more help from people who have done it.

@idrisshah any progress on the revisions?

2022-08-15 09:02 UTC, chenxuanyu commented
when I  merge this change in my code ，this test is pass ，but cause new qs ：

08-15 05:22:41.057  2803  4895 V OpenXR-Loader: Verbose [GENERAL | xrSubmitDebugUtilsMessageEXT | OpenXR-Loader] : Entering loader terminator
08-15 05:22:41.057  2803  4895 V OpenXR_Conformance: ../../../../framework/conformance_utils.cpp:257: FAILED:
08-15 05:22:41.057  2803  4895 V OpenXR_Conformance: explicitly with message:
08-15 05:22:41.057  2803  4895 V OpenXR_Conformance:   Conformance layer error: xrWaitFrame: New predicted display time 3162383585
08-15 05:22:41.057  2803  4895 V OpenXR_Conformance:   is less or equal to the previous predicted display time 3162391487

2022-08-15 14:12 UTC, rpavlik commented
That's a bug in your runtime: the predictedDisplayTime must be monotonically increasing.

2022-09-07 13:55 UTC, rpavlik commented
An updated version of this PR was merged and released with 1.0.25

2022-09-07 13:55 UTC, closed without merging