Fix incorrect handling of xrCreateSwapchainAndroidSurfaceKHR in template_gen_dispatch.cpp
KhronosGroup/OpenXR-CTS pull request #99
Opened 2024-11-12 03:26 UTC by quic-yli25

There is a bug in template_gen_dispatch.cpp that causes an error when destroying swapchain created by xrCreateSwapchainAndroidSurfaceKHR.

Here is an example. On Quest3, xrCreateSwapchainAndroidSurfaceKHR returns XR_SUCCESS, but xrDestroySwapchain returns XR_ERROR_HANDLE_INVALID.

```
CHECK(xrCreateSwapchainAndroidSurfaceKHR(session, &createInfo, &swapchain, &surface) == XR_SUCCESS);
CHECK(xrDestroySwapchain(swapchain) == XR_SUCCESS);
```

Check the log, there is an error message from conformance layer.

```
XrApiLayer_runtime_conformance: ERROR: Conformance Layer: Unknown handle used, created by unrecognized API call? Message = Encountered unknown XR_OBJECT_TYPE_SWAPCHAIN handle with value 519582891248
OpenXR_Conformance:   CHECK( xrDestroySwapchain(swapchain) == XR_SUCCESS )
OpenXR_Conformance: with expansion:
OpenXR_Conformance:   XR_ERROR_HANDLE_INVALID == XR_SUCCESS
```

template_gen_dispatch.cpp identifies a command as a create command if the function name includes "xrCreate" and the last parameter is a handle. xrCreateSwapchainAndroidSurfaceKHR is a special case because this is a create command but returned swapchain is not the last parameter. So template_gen_dispatch.cpp doesn't handle this command correctly.

Modify template_gen_dispatch.cpp, register handle state for swapchain created by xrCreateSwapchainAndroidSurfaceKHR.

2024-11-12 03:38 UTC, quic-yli25 commented
Hi @rpavlik. I create a MR for this issue we discussed, thanks!

2024-12-03 16:47 UTC, rpavlik commented
Can you make sure you have the CLA approved @quic-yli25 ?

2024-12-04 01:39 UTC, quic-yli25 commented
> Can you make sure you have the CLA approved @quic-yli25 ?

OK, I have signed CLA.

2024-12-06 18:25 UTC, rpavlik requested changes

2024-12-06 18:25 UTC, rpavlik commented on src/scripts/template_gen_dispatch.cpp
> +        RegisterHandleState(parentHandleState->CloneForChild(HandleToInt(* /*{penultimate_param_name}*/), XR_OBJECT_TYPE_SWAPCHAIN));
```suggestion
//#             set out_handle_param_name = cur_cmd.params[-2].name
        HandleState* const parentHandleState = GetHandleState(HandleStateKey{HandleToInt(/*{ first_handle_name }*/), XR_OBJECT_TYPE_SESSION});
        RegisterHandleState(parentHandleState->CloneForChild(HandleToInt(* /*{ out_handle_param_name }*/), XR_OBJECT_TYPE_SWAPCHAIN));
```

2024-12-09 01:43 UTC, quic-yli25 commented on src/scripts/template_gen_dispatch.cpp
> +        RegisterHandleState(parentHandleState->CloneForChild(HandleToInt(* /*{penultimate_param_name}*/), XR_OBJECT_TYPE_SWAPCHAIN));
Done.

2024-12-18 23:37 UTC, rpavlik approved these changes

2025-04-14 18:24 UTC, dsnopek approved these changes
I've also encountered this issue. And this PR fixes it for me!

2025-04-14 21:36 UTC, rpavlik commented
Thanks for the additional review!

2025-04-14 21:36 UTC, merged